//! `.ash/INDEX.md`: the one file an agent reads to decide which plans are
//! worth opening.
//!
//! It is generated, never hand-edited, for the reason every generated file
//! is: a hand-maintained index drifts out of sync and then confidently
//! reports things that are not true, which is worse than having no index. A
//! stale one is a `check` finding precisely so a forgotten regeneration
//! surfaces as an exit code rather than as a quietly wrong table.
//!
//! The rendering is byte-compatible with the `render_index` in
//! `scripts/ash.sh` that it replaces — attribution line included, for as long
//! as both exist. Two generators writing the same file cannot disagree by so
//! much as a character without each reporting the other's output as stale,
//! and `just qc` runs both during the changeover.

use std::path::Path;

use color_eyre::eyre::{Context, Result};

use super::corpus::{Corpus, Plan};

/// Named in the generated file so whoever opens it knows what to re-run.
///
/// Still the bash spelling, deliberately. `scripts/ash.sh` writes this same
/// file until phase 5 of plan `260920-wtburh` deletes it, and a differing
/// attribution would have each generator declare the other's index stale —
/// one of them inside `just qc`. TASK-041 flips this to `pinst harness index`
/// and regenerates, in the commit that removes the script.
pub const GENERATOR: &str = "scripts/ash.sh index";

/// Renders the whole table from plan frontmatter.
///
/// No sort key: plan ids start with a `yymmdd` date, so the corpus's plain
/// name order is already chronological. That is the entire reason the id is
/// `yymmdd` and not the friendlier `ddmmyy`.
pub fn render(corpus: &Corpus) -> String {
    let mut out = String::from("# Plan index\n\n");
    out.push_str(&format!(
        "<!-- Generated by {GENERATOR} from .ash/plans/*/README.md frontmatter. Do not hand-edit. -->\n\n"
    ));
    out.push_str("| Plan | ID | Status | Updated | Areas | Summary |\n");
    out.push_str("|------|----|--------|---------|-------|---------|\n");
    for plan in &corpus.plans {
        if let Some(row) = row(plan) {
            out.push_str(&row);
        }
    }
    out
}

/// A plan whose directory name does not parse has no row.
///
/// It is not skipped silently: `check` reports it as `plan.malformed-dir`.
/// Leaving it out here keeps the two jobs apart — the index renders what it
/// can read, the checker says what it could not.
fn row(plan: &Plan) -> Option<String> {
    let (id, slug) = plan.id.as_ref().zip(plan.slug.as_ref())?;
    let readme = plan.readme.as_ref()?;
    let field = |key: &str| readme.text(key).unwrap_or_default();
    Some(format!(
        "| [{slug}](plans/{}/README.md) | {id} | {} | {} | {} | {} |\n",
        plan.name,
        field("status"),
        field("updated"),
        field("areas"),
        field("summary"),
    ))
}

/// Whether the file on disk matches what the frontmatter would generate.
pub fn state(corpus: &Corpus) -> IndexState {
    let path = corpus.root.index_file();
    if !path.is_file() {
        return IndexState::Missing;
    }
    match std::fs::read_to_string(&path) {
        Ok(current) if current == render(corpus) => IndexState::Fresh,
        _ => IndexState::Stale,
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IndexState {
    Fresh,
    Stale,
    Missing,
}

/// Writes the index via a temporary file and a rename.
///
/// Not a plain truncate-and-write: a crash midway through leaves a truncated
/// index, and a half-written routing table is worse than a stale one because
/// nothing about it looks wrong.
pub fn write(corpus: &Corpus) -> Result<()> {
    let path = corpus.root.index_file();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("cannot create {}", parent.display()))?;
    }
    let temp = temp_path(&path);
    std::fs::write(&temp, render(corpus))
        .with_context(|| format!("cannot write {}", temp.display()))?;
    std::fs::rename(&temp, &path).with_context(|| format!("cannot replace {}", path.display()))
}

fn temp_path(path: &Path) -> std::path::PathBuf {
    let mut name = path.file_name().unwrap_or_default().to_os_string();
    name.push(".tmp");
    path.with_file_name(name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::harness::root::CorpusRoot;

    fn real() -> Corpus {
        Corpus::load(CorpusRoot::new(env!("CARGO_MANIFEST_DIR"))).unwrap()
    }

    /// The oracle this phase exists for: the incumbent bash generator wrote
    /// the committed `.ash/INDEX.md`, so reproducing it byte for byte is what
    /// proves the port did not quietly change a column. Exact, not
    /// modulo-anything — see `GENERATOR` for why even the attribution matches
    /// until the script is gone.
    #[test]
    fn reproduces_the_committed_index_byte_for_byte() {
        let corpus = real();
        let committed = std::fs::read_to_string(corpus.root.index_file()).unwrap();
        assert_eq!(render(&corpus), committed);
    }

    /// Every plan in the corpus gets exactly one row, and the header is three
    /// lines plus a blank — a cheap guard against a row being dropped by the
    /// `row()` filter without anyone noticing.
    #[test]
    fn every_readable_plan_gets_a_row() {
        let corpus = real();
        let rows = render(&corpus)
            .lines()
            .filter(|line| line.starts_with("| ["))
            .count();
        assert_eq!(rows, corpus.len());
    }

    #[test]
    fn a_list_valued_field_renders_comma_separated() {
        let corpus = real();
        let rendered = render(&corpus);
        assert!(
            rendered.contains("| cli, harness, agents |"),
            "areas should join with ', ':\n{rendered}"
        );
    }

    fn fixture() -> (tempfile::TempDir, Corpus) {
        let dir = tempfile::tempdir().unwrap();
        let plan = dir.path().join(".ash/plans/260919-qwerty-a-thing");
        std::fs::create_dir_all(&plan).unwrap();
        std::fs::write(
            plan.join("README.md"),
            "---\nid: 260919-qwerty\nslug: a-thing\nstatus: Proposed\n\
             created: 2026-09-19\nupdated: 2026-09-19\nareas: [cli, harness]\n\
             summary: A thing.\n---\n",
        )
        .unwrap();
        let corpus = Corpus::load(CorpusRoot::new(dir.path())).unwrap();
        (dir, corpus)
    }

    #[test]
    fn a_missing_index_is_distinguishable_from_a_stale_one() {
        let (_dir, corpus) = fixture();
        assert_eq!(state(&corpus), IndexState::Missing);

        write(&corpus).unwrap();
        assert_eq!(state(&corpus), IndexState::Fresh);

        std::fs::write(corpus.root.index_file(), "# Plan index\n").unwrap();
        assert_eq!(state(&corpus), IndexState::Stale);
    }

    /// Editing a plan's frontmatter must make the index stale — this is the
    /// signal `check` turns into `index.stale`.
    #[test]
    fn editing_frontmatter_makes_the_index_stale() {
        let (dir, corpus) = fixture();
        write(&corpus).unwrap();
        assert_eq!(state(&corpus), IndexState::Fresh);

        let readme = dir
            .path()
            .join(".ash/plans/260919-qwerty-a-thing/README.md");
        let edited = std::fs::read_to_string(&readme)
            .unwrap()
            .replace("summary: A thing.", "summary: A different thing.");
        std::fs::write(&readme, edited).unwrap();

        let reloaded = Corpus::load(CorpusRoot::new(dir.path())).unwrap();
        assert_eq!(state(&reloaded), IndexState::Stale);
    }

    #[test]
    fn writing_leaves_no_temporary_behind() {
        let (_dir, corpus) = fixture();
        write(&corpus).unwrap();
        let temp = temp_path(&corpus.root.index_file());
        assert!(!temp.exists(), "{} was left behind", temp.display());
    }
}
