//! Scaffolding a project's `.ash/` when a `pinst harness install --scope
//! project` finds none.
//!
//! The skills being installed are instructions for *producing* a corpus;
//! installing them into a repo with nowhere to write one leaves an agent to
//! invent the layout on the spot, which is exactly how the format drifts
//! from what `pinst harness check` expects (`REQ-007`). Every file here is
//! an ordinary `Step`, so `--dry-run` reports it like any other action, and
//! an existing file is never touched — this only fills in what is missing.

use std::path::Path;
use std::sync::Arc;

use color_eyre::eyre::Result;

use crate::core::plan::{Action, Plan, Step, StepKind};

const INDEX_STUB: &str = "# Plan index\n\n<!-- Generated by pinst harness index from .ash/plans/*/README.md frontmatter. Do not hand-edit. -->\n\n| Plan | ID | Status | Updated | Areas | Summary |\n|------|----|--------|---------|-------|---------|\n";

const LEARNINGS_STUB: &str = "# Distilled learnings\n\nLessons that generalize beyond the plan that produced them. Read this\nbefore planning new work.\n";

/// One step per missing piece of the corpus layout: `.ash/plans/`,
/// `INDEX.md`, `LEARNINGS.md`, `CHANGELOG.log`. A file that already exists
/// is left alone — this never overwrites a corpus that is merely young.
pub fn build_scaffold_plan(project_root: &Path) -> Result<Plan> {
    let mut plan = Plan::default();
    let ash = project_root.join(".ash");

    push_dir_step(&mut plan, "harness:corpus:plans", ash.join("plans"));
    push_file_step(
        &mut plan,
        "harness:corpus:index",
        ash.join("INDEX.md"),
        INDEX_STUB,
    );
    push_file_step(
        &mut plan,
        "harness:corpus:learnings",
        ash.join("LEARNINGS.md"),
        LEARNINGS_STUB,
    );
    push_file_step(
        &mut plan,
        "harness:corpus:changelog",
        ash.join("CHANGELOG.log"),
        "",
    );

    Ok(plan)
}

fn push_dir_step(plan: &mut Plan, id: &str, dir: std::path::PathBuf) {
    let description = format!("create {}", dir.display());
    if dir.is_dir() {
        plan.push(Step::new(id, StepKind::Config, description).skipped("already exists"));
        return;
    }
    // `.ash/plans/` is a directory with nothing to write inside it; a
    // zero-byte marker file gives `mkdir -p`-equivalent behavior through
    // the same `Action::Write` every other step already uses, without
    // adding a directory-creation action type for one caller.
    plan.push(
        Step::new(id, StepKind::Config, description).actions(vec![Action::Write {
            target: dir.join(".gitkeep"),
            bytes: 0,
            content: Arc::new(Vec::new()),
        }]),
    );
}

fn push_file_step(plan: &mut Plan, id: &str, path: std::path::PathBuf, content: &str) {
    let description = format!("create {}", path.display());
    if path.is_file() {
        plan.push(Step::new(id, StepKind::Config, description).skipped("already exists"));
        return;
    }
    let bytes = content.as_bytes().to_vec();
    plan.push(
        Step::new(id, StepKind::Config, description).actions(vec![Action::Write {
            target: path,
            bytes: bytes.len(),
            content: Arc::new(bytes),
        }]),
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_bare_directory_gets_every_scaffold_file() {
        let dir = tempfile::tempdir().unwrap();
        let plan = build_scaffold_plan(dir.path()).unwrap();
        assert_eq!(plan.pending_count(), 4);
    }

    #[test]
    fn an_existing_ash_directory_is_never_overwritten() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(dir.path().join(".ash/plans")).unwrap();
        std::fs::write(dir.path().join(".ash/INDEX.md"), "custom content").unwrap();

        let plan = build_scaffold_plan(dir.path()).unwrap();
        let index_step = plan
            .steps
            .iter()
            .find(|s| s.id == "harness:corpus:index")
            .unwrap();
        assert!(
            !index_step.is_pending(),
            "an existing INDEX.md must be skipped"
        );
        let plans_step = plan
            .steps
            .iter()
            .find(|s| s.id == "harness:corpus:plans")
            .unwrap();
        assert!(!plans_step.is_pending());
    }
}
